// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/reward/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// 메시지 정의
type MsgRewardSolarPower struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRewardSolarPower) Reset()         { *m = MsgRewardSolarPower{} }
func (m *MsgRewardSolarPower) String() string { return proto.CompactTextString(m) }
func (*MsgRewardSolarPower) ProtoMessage()    {}
func (*MsgRewardSolarPower) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fab18f39c554771, []int{0}
}
func (m *MsgRewardSolarPower) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRewardSolarPower.Unmarshal(m, b)
}
func (m *MsgRewardSolarPower) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRewardSolarPower.Marshal(b, m, deterministic)
}
func (m *MsgRewardSolarPower) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRewardSolarPower.Merge(m, src)
}
func (m *MsgRewardSolarPower) XXX_Size() int {
	return xxx_messageInfo_MsgRewardSolarPower.Size(m)
}
func (m *MsgRewardSolarPower) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRewardSolarPower.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRewardSolarPower proto.InternalMessageInfo

func (m *MsgRewardSolarPower) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRewardSolarPower) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgRewardSolarPower) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgRewardSolarPowerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRewardSolarPowerResponse) Reset()         { *m = MsgRewardSolarPowerResponse{} }
func (m *MsgRewardSolarPowerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRewardSolarPowerResponse) ProtoMessage()    {}
func (*MsgRewardSolarPowerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fab18f39c554771, []int{1}
}
func (m *MsgRewardSolarPowerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRewardSolarPowerResponse.Unmarshal(m, b)
}
func (m *MsgRewardSolarPowerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRewardSolarPowerResponse.Marshal(b, m, deterministic)
}
func (m *MsgRewardSolarPowerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRewardSolarPowerResponse.Merge(m, src)
}
func (m *MsgRewardSolarPowerResponse) XXX_Size() int {
	return xxx_messageInfo_MsgRewardSolarPowerResponse.Size(m)
}
func (m *MsgRewardSolarPowerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRewardSolarPowerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRewardSolarPowerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRewardSolarPower)(nil), "cosmos.reward.v1beta1.MsgRewardSolarPower")
	proto.RegisterType((*MsgRewardSolarPowerResponse)(nil), "cosmos.reward.v1beta1.MsgRewardSolarPowerResponse")
}

func init() { proto.RegisterFile("cosmos/reward/v1beta1/tx.proto", fileDescriptor_4fab18f39c554771) }

var fileDescriptor_4fab18f39c554771 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0xe5, 0x46, 0xea, 0xa7, 0xcf, 0x13, 0x0a, 0x02, 0x45, 0xe5, 0x47, 0x28, 0x13, 0xb4,
	0xaa, 0xad, 0x96, 0xad, 0x23, 0x7b, 0x25, 0x14, 0x36, 0x96, 0xea, 0x24, 0xb1, 0x4c, 0x44, 0xe3,
	0x63, 0xf9, 0xb8, 0xb4, 0xac, 0xdc, 0x02, 0xf7, 0xc1, 0xc8, 0x8d, 0x70, 0x0b, 0x5c, 0x08, 0x4a,
	0x9c, 0x4c, 0x64, 0x60, 0xb2, 0x5e, 0x3d, 0x7e, 0xce, 0xb1, 0x5f, 0x7e, 0x59, 0x20, 0xd5, 0x48,
	0xd2, 0xa9, 0x3d, 0xb8, 0x52, 0xbe, 0x2c, 0x72, 0xe5, 0x61, 0x21, 0xfd, 0x41, 0x58, 0x87, 0x1e,
	0xe3, 0x93, 0xc0, 0x45, 0xe0, 0xa2, 0xe3, 0x93, 0x73, 0x8d, 0xa8, 0xb7, 0x4a, 0x82, 0xad, 0x24,
	0x18, 0x83, 0x1e, 0x7c, 0x85, 0x86, 0x82, 0x94, 0x02, 0x3f, 0x5e, 0x93, 0xce, 0x5a, 0xe5, 0x01,
	0xb7, 0xe0, 0xee, 0x71, 0xaf, 0x5c, 0x9c, 0xf0, 0x7f, 0x85, 0x53, 0xe0, 0xd1, 0x25, 0xec, 0x8a,
	0x5d, 0xff, 0xcf, 0xfa, 0xd8, 0x10, 0x28, 0x4b, 0xa7, 0x88, 0x92, 0x51, 0x20, 0x5d, 0x8c, 0x4f,
	0xf9, 0x18, 0x6a, 0xdc, 0x19, 0x9f, 0x44, 0x2d, 0xe8, 0x52, 0x7a, 0xc1, 0xcf, 0x06, 0x56, 0x64,
	0x8a, 0x2c, 0x1a, 0x52, 0xcb, 0x4f, 0xc6, 0xa3, 0x35, 0xe9, 0xf8, 0x83, 0xf1, 0xa3, 0x5f, 0xef,
	0x98, 0x8a, 0xc1, 0x4f, 0x89, 0x81, 0x81, 0x93, 0xe5, 0xdf, 0xef, 0xf6, 0xcb, 0xd3, 0xd5, 0xdb,
	0xd7, 0xf7, 0xfb, 0x68, 0x96, 0xde, 0xc8, 0xe1, 0x72, 0x43, 0xdc, 0x50, 0x63, 0x6e, 0x6c, 0xa3,
	0xb6, 0x42, 0xb4, 0x62, 0xd3, 0xbb, 0xf9, 0xe3, 0x4c, 0x57, 0xfe, 0x69, 0x97, 0x8b, 0x02, 0xeb,
	0xde, 0x0f, 0xc7, 0x9c, 0xca, 0x67, 0x79, 0xe8, 0x87, 0xf9, 0x57, 0xab, 0x28, 0x1f, 0xb7, 0x85,
	0xdf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x7a, 0x95, 0xac, 0xc7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RewardSolarPower(ctx context.Context, in *MsgRewardSolarPower, opts ...grpc.CallOption) (*MsgRewardSolarPowerResponse, error)
}

type msgClient struct {
	cc *grpc.ClientConn
}

func NewMsgClient(cc *grpc.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RewardSolarPower(ctx context.Context, in *MsgRewardSolarPower, opts ...grpc.CallOption) (*MsgRewardSolarPowerResponse, error) {
	out := new(MsgRewardSolarPowerResponse)
	err := c.cc.Invoke(ctx, "/cosmos.reward.v1beta1.Msg/RewardSolarPower", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RewardSolarPower(context.Context, *MsgRewardSolarPower) (*MsgRewardSolarPowerResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RewardSolarPower(ctx context.Context, req *MsgRewardSolarPower) (*MsgRewardSolarPowerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RewardSolarPower not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RewardSolarPower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRewardSolarPower)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RewardSolarPower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.reward.v1beta1.Msg/RewardSolarPower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RewardSolarPower(ctx, req.(*MsgRewardSolarPower))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.reward.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RewardSolarPower",
			Handler:    _Msg_RewardSolarPower_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/reward/v1beta1/tx.proto",
}
